export default {
  api: {
    server: 'http://172.32.1.144/api'
  },
  markdown: {
    gfm: true,
    tables: true,
    breaks: false,
    pedantic: false,
    smartLists: true,
    smartypants: false,
  },
  langTable: [{
    value: '0',
    label: 'C++'
  }, {
    value: '1',
    label: 'C++11'
  }, {
    value: '2',
    label: 'C++14'
  }, {
    value: '3',
    label: 'C++17'
  }, {
    value: '4',
    label: 'C++20'
  }, {
    value: '5',
    label: 'C'
  }, {
    value: '6',
    label: 'C#'
  }, {
    value: '7',
    label: 'Clang'
  }, {
    value: '8',
    label: 'Clang11'
  }, {
    value: '9',
    label: 'Clang14'
  }, {
    value: '10',
    label: 'Clang17'
  }, {
    value: '11',
    label: 'Clang20'
  }, {
    value: '12',
    label: 'Rust'
  }, {
    value: '13',
    label: 'Python2'
  }, {
    value: '14',
    label: 'Python3'
  }, {
    value: '15',
    label: 'Pascal'
  }, {
    value: '16',
    label: 'Go'
  }, {
    value: '17',
    label: 'Ruby'
  }, {
    value: '18',
    label: 'Java'
  }],
  captchaKeyMax: 2000000000
};