name: Lint Check CI

on: [push, release]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        node-version: [14.5]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        working-directory: .
        run: npm install

      - name: Run Lint
        run: |
          npm run lint -- --no-fix
          npm run lint:css
      
      - name: Build Code
        run: |
          npm run build
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        

        
